---
title: Clean architecture
namespace: CleanArchitecture
---
graph TD
    Infrastructure --> Domain
    Infrastructure --> Application
    Presentation --> Application
    Presentation --> Domain
    Application --> Domain